---
version: '3.8'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - dataportainer:/data
    
    ## FACULTATIF - configuration with Traefik
    #labels:
      #traefik.enable: true
      #traefik.http.routers.portainer-http.entrypoints: "web"
      #traefik.http.routers.portainer.rule: Host(`portainer.czs.local`)
 volumes:
   dataportainer: